openapi: 3.0.0
info:
  title: Movies API
  version: 0.3.7

servers:
  - url: http://localhost:4000

paths:
  /v1/users:
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"
            example:
              name: "Nikita"
              email: "obrikash@gmail.com"
              password: "12345678"
      responses:
        "201":
          description: Successfully created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreated'
              example:
                user:
                  id: 10
                  created_at: "2025-03-28T12:40:41+03:00"
                  name: "Nikita"
                  email: "obrikash@gmail.com"
                  activated: false











components:
  # ------------------------------
  # Reusable schemas (data models)
  # ------------------------------
  schemas:
    UserForm:
      type: object
      properties:
          name:
            type: string
          email:
            type: string
          password:
            type: string
    UserCreated:
      type: object
      properties:
        user:
                type: object
                properties:
                  id:
                    type: string
                    format: int64
                  created_at:
                    type: string
                    format: date
                  name:
                    type: string
                  email:
                    type: string
                  activated:
                    type: boolean
          

